//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenTicket.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoldenTicketText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoldenTicketText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldenTicket.Resources.GoldenTicketText", typeof(GoldenTicketText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information provided above is correct and I understand that filing documents containing false information with the government is illegal. (RIGL 11-18-1)..
        /// </summary>
        public static string AgreementInformationIsCorrect {
            get {
                return ResourceManager.GetString("AgreementInformationIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that I can be reached at the phone numbers listed in this application on {0} if my child is chosen in the state lottery to participate in the state Pre-K program..
        /// </summary>
        public static string AgreementReachableOnNotificationDate {
            get {
                return ResourceManager.GetString("AgreementReachableOnNotificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that if my child is chosen for the state Pre-K program, I am responsible for providing regular transportation to and from the program which ensures my child&amp;rsquo;s attendance each day. If my child is absent for unexcused reasons (including family vacations) for 20 or more school days, I understand that my child will likely lose their slot in the state Pre-K program and it will be given to the next child on the state Pre-K enrollment list..
        /// </summary>
        public static string AgreementResponsibleForTransportation {
            get {
                return ResourceManager.GetString("AgreementResponsibleForTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact.
        /// </summary>
        public static string AlternateContact {
            get {
                return ResourceManager.GetString("AlternateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied to.
        /// </summary>
        public static string AppliedTo {
            get {
                return ResourceManager.GetString("AppliedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the dollar amount of the monthly household income (no commas).
        /// </summary>
        public static string AverageHouseholdIncomeInstructions {
            get {
                return ResourceManager.GetString("AverageHouseholdIncomeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average monthly income (combined total of all income earning household members).
        /// </summary>
        public static string AverageMonthlyIncomeAndExplanation {
            get {
                return ResourceManager.GetString("AverageMonthlyIncomeAndExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday (mm/dd/yyyy format).
        /// </summary>
        public static string BirthdayAndInstructions {
            get {
                return ResourceManager.GetString("BirthdayAndInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By submitting this form, I attest that:.
        /// </summary>
        public static string BySubmittingThisForm {
            get {
                return ResourceManager.GetString("BySubmittingThisForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one or more schools that {0} will be considered for enrollment..
        /// </summary>
        public static string ChooseOneOrMoreSchools {
            get {
                return ResourceManager.GetString("ChooseOneOrMoreSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code.
        /// </summary>
        public static string ConfirmationCode {
            get {
                return ResourceManager.GetString("ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your confirmation number is {0}.
        /// </summary>
        public static string ConfirmationNumberIs {
            get {
                return ResourceManager.GetString("ConfirmationNumberIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian email address.
        /// </summary>
        public static string Contact1Email {
            get {
                return ResourceManager.GetString("Contact1Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian first name.
        /// </summary>
        public static string Contact1FirstName {
            get {
                return ResourceManager.GetString("Contact1FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian last name.
        /// </summary>
        public static string Contact1LastName {
            get {
                return ResourceManager.GetString("Contact1LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian phone number.
        /// </summary>
        public static string Contact1Phone {
            get {
                return ResourceManager.GetString("Contact1Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian relationship to child.
        /// </summary>
        public static string Contact1Relationship {
            get {
                return ResourceManager.GetString("Contact1Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact email address.
        /// </summary>
        public static string Contact2Email {
            get {
                return ResourceManager.GetString("Contact2Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact first name.
        /// </summary>
        public static string Contact2FirstName {
            get {
                return ResourceManager.GetString("Contact2FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact last name.
        /// </summary>
        public static string Contact2LastName {
            get {
                return ResourceManager.GetString("Contact2LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact phone number.
        /// </summary>
        public static string Contact2Phone {
            get {
                return ResourceManager.GetString("Contact2Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact relationship to child.
        /// </summary>
        public static string Contact2Relationship {
            get {
                return ResourceManager.GetString("Contact2Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll another family member.
        /// </summary>
        public static string EnrollAnotherFamilyMember {
            get {
                return ResourceManager.GetString("EnrollAnotherFamilyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        public static string Guardian {
            get {
                return ResourceManager.GetString("Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian information.
        /// </summary>
        public static string GuardianInformation {
            get {
                return ResourceManager.GetString("GuardianInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly income must be entered or selected..
        /// </summary>
        public static string HouseholdIncomeMissing {
            get {
                return ResourceManager.GetString("HouseholdIncomeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household information.
        /// </summary>
        public static string HouseholdInformation {
            get {
                return ResourceManager.GetString("HouseholdInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household members.
        /// </summary>
        public static string HouseholdMembers {
            get {
                return ResourceManager.GetString("HouseholdMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of household members must be entered and must be at least 2 people..
        /// </summary>
        public static string HouseholdMembersMissingOrInvalid {
            get {
                return ResourceManager.GetString("HouseholdMembersMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household monthly income.
        /// </summary>
        public static string HouseholdMonthlyIncome {
            get {
                return ResourceManager.GetString("HouseholdMonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, please contact {0} at {1}..
        /// </summary>
        public static string HowToContact {
            get {
                return ResourceManager.GetString("HowToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is not an eligible age. He/she must be 4 years old on 9/1/{0}..
        /// </summary>
        public static string IneligibleBirthday {
            get {
                return ResourceManager.GetString("IneligibleBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only have letters, spaces, dashes, and apostrophes..
        /// </summary>
        public static string LettersSpacesAndApostrophesOnlyError {
            get {
                return ResourceManager.GetString("LettersSpacesAndApostrophesOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one school must be selected..
        /// </summary>
        public static string NoSchoolSelected {
            get {
                return ResourceManager.GetString("NoSchoolSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people in your household.
        /// </summary>
        public static string NumberOfPeopleInHousehold {
            get {
                return ResourceManager.GetString("NumberOfPeopleInHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide information about the number of people in your household and the combined income of all household members..
        /// </summary>
        public static string NumberOfPeopleInHouseholdInstructions {
            get {
                return ResourceManager.GetString("NumberOfPeopleInHouseholdInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or more.
        /// </summary>
        public static string OrMore {
            get {
                return ResourceManager.GetString("OrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 Application for Pre-Kindergarten.
        /// </summary>
        public static string ParentHeaderTitle {
            get {
                return ResourceManager.GetString("ParentHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to the lottery.
        /// </summary>
        public static string ParentIntroApplyToTheLotteryButton {
            get {
                return ResourceManager.GetString("ParentIntroApplyToTheLotteryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further assistance, email &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt; or call him at &lt;a href=&quot;tel:{2}&quot;&gt;{2}&lt;/a&gt;..
        /// </summary>
        public static string ParentIntroContactInfo {
            get {
                return ResourceManager.GetString("ParentIntroContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your interest in enrolling your student in one of the state&apos;s pre-kindergarten classes. Due to demand, students must be selected for enrollment through a state-supervised lottery..
        /// </summary>
        public static string ParentIntroPageIntro {
            get {
                return ResourceManager.GetString("ParentIntroPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications to the statewide lottery are accepted until August 15th. Selected applicants will be notified via phone on August 16th..
        /// </summary>
        public static string ParentIntroWhatHappensNextBody {
            get {
                return ResourceManager.GetString("ParentIntroWhatHappensNextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens next?.
        /// </summary>
        public static string ParentIntroWhatHappensNextHeader {
            get {
                return ResourceManager.GetString("ParentIntroWhatHappensNextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be eligible for enrollment, you child must turn 4 years of age by September 1 and live in the community in which their pre-k program is located. A copy of the child&apos;s birth certificate and proof of residency will be required upon enrollment..
        /// </summary>
        public static string ParentIntroWhatYouNeedToKnowBody {
            get {
                return ResourceManager.GetString("ParentIntroWhatYouNeedToKnowBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you need to know.
        /// </summary>
        public static string ParentIntroWhatYouNeedToKnowHeader {
            get {
                return ResourceManager.GetString("ParentIntroWhatYouNeedToKnowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone (###-###-####).
        /// </summary>
        public static string PhoneAndFormat {
            get {
                return ResourceManager.GetString("PhoneAndFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be 10 numbers long (area code +phone number)..
        /// </summary>
        public static string PhoneValidationError {
            get {
                return ResourceManager.GetString("PhoneValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide some basic information about {0}&apos;s primary guardian..
        /// </summary>
        public static string PleaseProvideBasicInformationAbout {
            get {
                return ResourceManager.GetString("PleaseProvideBasicInformationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be entered..
        /// </summary>
        public static string PropertyMissing {
            get {
                return ResourceManager.GetString("PropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide some basic information about the student you wish to enter into the lottery..
        /// </summary>
        public static string ProvideBasicStudentInformation {
            get {
                return ResourceManager.GetString("ProvideBasicStudentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship to {0}.
        /// </summary>
        public static string RelationshipToPerson {
            get {
                return ResourceManager.GetString("RelationshipToPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review application.
        /// </summary>
        public static string ReviewApplication {
            get {
                return ResourceManager.GetString("ReviewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a moment to review the information you&amp;rsquo;ve entered, below, before submitting your application..
        /// </summary>
        public static string ReviewInstructions {
            get {
                return ResourceManager.GetString("ReviewInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schools.
        /// </summary>
        public static string Schools {
            get {
                return ResourceManager.GetString("Schools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School selection.
        /// </summary>
        public static string SchoolSelection {
            get {
                return ResourceManager.GetString("SchoolSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepfather.
        /// </summary>
        public static string Stepfather {
            get {
                return ResourceManager.GetString("Stepfather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepmother.
        /// </summary>
        public static string Stepmother {
            get {
                return ResourceManager.GetString("Stepmother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re on step {0} of {1}:.
        /// </summary>
        public static string StepXOfY {
            get {
                return ResourceManager.GetString("StepXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address (line 1).
        /// </summary>
        public static string StreetAddress1 {
            get {
                return ResourceManager.GetString("StreetAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address (line 2).
        /// </summary>
        public static string StreetAddress2 {
            get {
                return ResourceManager.GetString("StreetAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only have letters, numbers, periods, #s, dashes, and spaces..
        /// </summary>
        public static string StreetAddressValidationError {
            get {
                return ResourceManager.GetString("StreetAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student birthday.
        /// </summary>
        public static string StudentBirthday {
            get {
                return ResourceManager.GetString("StudentBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student city.
        /// </summary>
        public static string StudentCity {
            get {
                return ResourceManager.GetString("StudentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student first name.
        /// </summary>
        public static string StudentFirstName {
            get {
                return ResourceManager.GetString("StudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student gender.
        /// </summary>
        public static string StudentGender {
            get {
                return ResourceManager.GetString("StudentGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student information.
        /// </summary>
        public static string StudentInformation {
            get {
                return ResourceManager.GetString("StudentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student last name.
        /// </summary>
        public static string StudentLastName {
            get {
                return ResourceManager.GetString("StudentLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student middle name.
        /// </summary>
        public static string StudentMiddleName {
            get {
                return ResourceManager.GetString("StudentMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student street address (line 1).
        /// </summary>
        public static string StudentStreetAddress1 {
            get {
                return ResourceManager.GetString("StudentStreetAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student street address (line 2).
        /// </summary>
        public static string StudentStreetAddress2 {
            get {
                return ResourceManager.GetString("StudentStreetAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ZIP code.
        /// </summary>
        public static string StudentZipCode {
            get {
                return ResourceManager.GetString("StudentZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit application.
        /// </summary>
        public static string SubmitApplication {
            get {
                return ResourceManager.GetString("SubmitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully entered {0} {1} into the state-wide lottery for pre-kindergarten enrollment. If selected, you will be notified via phone on {2}..
        /// </summary>
        public static string SuccessfullyEnteredStudent {
            get {
                return ResourceManager.GetString("SuccessfullyEnteredStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have 5 numbers (and can optionally have a trailing dash with 4 more numbers)..
        /// </summary>
        public static string ZipCodeValidationError {
            get {
                return ResourceManager.GetString("ZipCodeValidationError", resourceCulture);
            }
        }
    }
}
