//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenTicketResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoldenTicketText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoldenTicketText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldenTicket.Resources.GoldenTicketText", typeof(GoldenTicketText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code.
        /// </summary>
        public static string ConfirmationCode {
            get {
                return ResourceManager.GetString("ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian email address.
        /// </summary>
        public static string Contact1Email {
            get {
                return ResourceManager.GetString("Contact1Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian first name.
        /// </summary>
        public static string Contact1FirstName {
            get {
                return ResourceManager.GetString("Contact1FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian last name.
        /// </summary>
        public static string Contact1LastName {
            get {
                return ResourceManager.GetString("Contact1LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian phone number.
        /// </summary>
        public static string Contact1Phone {
            get {
                return ResourceManager.GetString("Contact1Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian relationship to child.
        /// </summary>
        public static string Contact1Relationship {
            get {
                return ResourceManager.GetString("Contact1Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact email address.
        /// </summary>
        public static string Contact2Email {
            get {
                return ResourceManager.GetString("Contact2Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact first name.
        /// </summary>
        public static string Contact2FirstName {
            get {
                return ResourceManager.GetString("Contact2FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact last name.
        /// </summary>
        public static string Contact2LastName {
            get {
                return ResourceManager.GetString("Contact2LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact phone number.
        /// </summary>
        public static string Contact2Phone {
            get {
                return ResourceManager.GetString("Contact2Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate contact relationship to child.
        /// </summary>
        public static string Contact2Relationship {
            get {
                return ResourceManager.GetString("Contact2Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average monthly income must be entered or selected..
        /// </summary>
        public static string HouseholdIncomeMissing {
            get {
                return ResourceManager.GetString("HouseholdIncomeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household members.
        /// </summary>
        public static string HouseholdMembers {
            get {
                return ResourceManager.GetString("HouseholdMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of household members must be entered and must be at least 2 people..
        /// </summary>
        public static string HouseholdMembersMissingOrInvalid {
            get {
                return ResourceManager.GetString("HouseholdMembersMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household monthly income.
        /// </summary>
        public static string HouseholdMonthlyIncome {
            get {
                return ResourceManager.GetString("HouseholdMonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is not an eligible age. He/she must be 4 years old on 9/1/{0}..
        /// </summary>
        public static string IneligibleBirthday {
            get {
                return ResourceManager.GetString("IneligibleBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only have letters, spaces, dashes, and apostrophes..
        /// </summary>
        public static string LettersSpacesAndApostrophesOnlyError {
            get {
                return ResourceManager.GetString("LettersSpacesAndApostrophesOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one school must be selected..
        /// </summary>
        public static string NoSchoolSelected {
            get {
                return ResourceManager.GetString("NoSchoolSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 Application for Pre-Kindergarten.
        /// </summary>
        public static string ParentHeaderTitle {
            get {
                return ResourceManager.GetString("ParentHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to the lottery.
        /// </summary>
        public static string ParentIntroApplyToTheLotteryButton {
            get {
                return ResourceManager.GetString("ParentIntroApplyToTheLotteryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further assistance, email Franklin Brito or call him at 401-222-8184..
        /// </summary>
        public static string ParentIntroContactInfo {
            get {
                return ResourceManager.GetString("ParentIntroContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your interest in enrolling your student in one of the state&apos;s pre-kindergarten classes. Due to demand, students must be selected for enrollment through a state-supervised lottery..
        /// </summary>
        public static string ParentIntroPageIntro {
            get {
                return ResourceManager.GetString("ParentIntroPageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications to the statewide lottery are accepted until August 15th. Selected applicants will be notified via phone on August 16th..
        /// </summary>
        public static string ParentIntroWhatHappensNextBody {
            get {
                return ResourceManager.GetString("ParentIntroWhatHappensNextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens next?.
        /// </summary>
        public static string ParentIntroWhatHappensNextHeader {
            get {
                return ResourceManager.GetString("ParentIntroWhatHappensNextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be eligible for enrollment, you child must turn 4 years of age by September 1 and live in the community in which their pre-k program is located. A copy of the child&apos;s birth certificate and proof of residency will be required upon enrollment..
        /// </summary>
        public static string ParentIntroWhatYouNeedToKnowBody {
            get {
                return ResourceManager.GetString("ParentIntroWhatYouNeedToKnowBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you need to know.
        /// </summary>
        public static string ParentIntroWhatYouNeedToKnowHeader {
            get {
                return ResourceManager.GetString("ParentIntroWhatYouNeedToKnowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be 10 numbers long (area code +phone number)..
        /// </summary>
        public static string PhoneValidationError {
            get {
                return ResourceManager.GetString("PhoneValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be entered..
        /// </summary>
        public static string PropertyMissing {
            get {
                return ResourceManager.GetString("PropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only have letters, numbers, periods, #s, dashes, and spaces..
        /// </summary>
        public static string StreetAddressValidationError {
            get {
                return ResourceManager.GetString("StreetAddressValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student birthday.
        /// </summary>
        public static string StudentBirthday {
            get {
                return ResourceManager.GetString("StudentBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student city.
        /// </summary>
        public static string StudentCity {
            get {
                return ResourceManager.GetString("StudentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student first name.
        /// </summary>
        public static string StudentFirstName {
            get {
                return ResourceManager.GetString("StudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student gender.
        /// </summary>
        public static string StudentGender {
            get {
                return ResourceManager.GetString("StudentGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student last name.
        /// </summary>
        public static string StudentLastName {
            get {
                return ResourceManager.GetString("StudentLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student middle name.
        /// </summary>
        public static string StudentMiddleName {
            get {
                return ResourceManager.GetString("StudentMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student street address (line 1).
        /// </summary>
        public static string StudentStreetAddress1 {
            get {
                return ResourceManager.GetString("StudentStreetAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student street address (line 2).
        /// </summary>
        public static string StudentStreetAddress2 {
            get {
                return ResourceManager.GetString("StudentStreetAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ZIP code.
        /// </summary>
        public static string StudentZipCode {
            get {
                return ResourceManager.GetString("StudentZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have 5 numbers (and can optionally have a trailing dash with 4 more numbers)..
        /// </summary>
        public static string ZipCodeValidationError {
            get {
                return ResourceManager.GetString("ZipCodeValidationError", resourceCulture);
            }
        }
    }
}
